from typing import Protocol

import h5py


class DataSchema(Protocol):
    def insert(self, child: "DataSchema", path: str): ...
    def add_child(self, child: "DataSchema", name: str): ...
    def allocate(self, group: h5py.File | h5py.Group): ...
    def verify(self): ...
    def into_writer(self): ...


class DataWriter(Protocol):
    def write(self, group: h5py.File | h5py.Group): ...


class Writeable(Protocol):
    def make_schema(self, name: str) -> DataSchema: ...
