from typing import Protocol
import h5py



class DataSchema(Protocol):
    def insert(self, child: "DataSchema", path: str, type_: str): ...
    def add_child(self, child: "DataSchema", name: str, type_: str): ...
    def allocate(self, group: h5py.File | h5py.Group): ...
    def verify(self): ...
    def into_writer(self, source: h5py.File | h5py.Group): ...
    

class DataWriter(Protocol):
    schema: DataSchema
    def write(self, group: h5py.File | h5py.Group): ...
    
