# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.15.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        additional_dependencies: ["numpy"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.11.9'
    hooks:
        - id: ruff-format
        - id: ruff
          args: ["--fix"]
        - id: ruff
          args: ["--select", "I", "--fix"]
