name: Merge Request Checks
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  test:
    uses: ./.github/workflows/build.yaml


