name: Build Docs
on:
  pull_request:
    branches:
      - main
    paths:
      - 'docs/**'
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "/docs"
