name: merge CI
on:
  push:
    branches:
      - main
jobs:
  build:
    uses: ./.github/workflows/build.yaml
  docker:
    uses: ./.github/workflows/docker.yaml
    with:
      tags: docker.io/astropatty/opencosmo:dev
      push: true
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-access-key: ${{ secrets.DOCKER_ACCESS_KEY }}
