name: merge CI
on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  build:
    uses: ./.github/workflows/build.yaml
    with:
      push-docker: true
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-access-key: ${{ secrets.DOCKER_ACCESS_KEY }}
      
