name: opencosmo CI
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  test:
    uses: ./.github/workflows/test.yaml
    secrets: inherit
  build:
    uses: ./.github/workflows/build.yaml
  check-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: git fetch origin ${{ github.event.pull_request.base.ref }}
          

      - name: Check for new files
        id: check_files
        run: |
          NEWS_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} -- "changes")
          if [ -z "$NEWS_FILES" ]; then
            echo "PRs must include a news fragment describing their changes in /changes"
            exit 1
          else
            echo "Found news files ${NEWS_FILES}"
          fi

          echo "NEWS_FILES=${NEWS_FILES}" >> "$GITHUB_OUTPUT"

      - name: check extensions
        run: |
          ALLOWED_EXTENSIONS=("feature.rst" "bugfix.rst" "doc.rst" "removal.rst" "misc.rst")
          for file in ${{ steps.check_files.outputs.NEWS_FILES }}; do
            valid_extension=false
            for ext in "${ALLOWED_EXTENSIONS[@]"; do
              if [[ "$file" == *"$ext" ]]; then
                valid_extension=true
                break
              fi
            done
            if ! $valid_extension; then
              echo "File $file does not have a valid extension"
              echo "Must be one of .feature.rst, .bugfix.rst, .doc.rst, .removal.rst, .misc.rst"
              exit 1
            fi
          done



