name: release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
jobs:
  check-pyproject-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - uses: snok/install-poetry@v1
      - name: get pyproject.toml version
        run: |
          PROJECT_VERSION=$(poetry version --short) 
          echo "PROJECT_VERSION=$PROJECT_VERSION" >> $GITHUB_ENV
      - name: check version
        run: |
          echo "Checking version"
          echo "PROJECT_VERSION=$PROJECT_VERSION"
          echo "TAG=${{ github.ref }}"
          TAG_NAME="${GITHUB_REF#refs/tags/}"
          if [[ "$PROJECT_VERSION" != "$TAG_NAME"]]; then
            echo "Version mismatch"
            exit 1
          fi
          echo "Version match"

  publish-package:
    runs-on: ubuntu-latest
    needs: check-pyproject-version
    steps: 
      - uses: actions/checkout@v4
      - uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
  
  release-github-package:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
      - uses: actions/download-artifact@v4
      - uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}

      
      


